USE web;

CREATE TABLE web (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(10) NOT NULL DEFAULT '',
  age TINYINT UNSIGNED NOT NULL DEFAULT 0,
  description VARCHAR(200) NOT NULL DEFAULT '',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;